# 다중 퍼셉트론-XQR

In [2]:
import numpy as np
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


# 실행할 때마다 같은 결과를 출력하기 위한 seed 값 설정

In [3]:
seed = 123
np.random.seed(seed)
tf.set_random_seed(seed)

In [6]:

# x, y의 데이터 값
x_data = np.array([[0, 0],[0, 1],[1, 0],[1, 1]]) 
y_data = np.array([0, 1, 1, 0]).reshape(-1,1)
print(x_data.shape, y_data.shape)

(4, 2) (4, 1)


In [7]:
X = tf.placeholder(tf.float32, [None, 2])
Y = tf.placeholder(tf.float32, [None, 1])

# 다음 layer1을 만든다.

In [8]:
# Layer 1
W1 = tf.Variable(tf.random_normal([2, 2]), dtype=tf.float32)
b1 = tf.Variable(tf.random_normal([2]), dtype=tf.float32)
L1 = tf.sigmoid(tf.matmul(X, W1) + b1)

In [10]:
# Layer 2
W2 = tf.Variable(tf.random_normal([2, 1]), dtype=tf.float32)
b2 = tf.Variable(tf.random_normal([1]), dtype=tf.float32)
hypo = tf.sigmoid(tf.matmul(L1, W2) + b2)

In [12]:
# Cost - Binary Cross Entropy를 정의해준다
cost = -tf.reduce_mean(Y * tf.log(hypo) + (1.-Y) * tf.log(1.-hypo))

In [13]:
# Optimizer - Adam
lr = 0.1
train = tf.train.AdamOptimizer(learning_rate=lr).minimize(cost)

In [15]:
# Accuracy 계산
predicted = tf.cast(hypo > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

In [17]:
# 학습
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())
    for step in range(50000):
        _, cost_val = sess.run([train, cost], feed_dict={X: x_data, Y: y_data})
        if step % 1000 == 0:
            print(step, cost_val)
            
    # Accuracy report
    h, p, a = sess.run([hypo, predicted, accuracy], feed_dict={X: x_data, Y: y_data}) 
    print(f"\nHypothesis:\n{h} \nPredicted:\n{p} \nAccuracy:\n{a}")
    #로핑 끝난후 weight와 bias를 출력
    # Weight, bias
    W1_, b1_, W2_, b2_ = sess.run([W1, b1, W2, b2])
    print(f"\nW1:\n{W1_} \nb1:\n{b1_} \nW2:\n{W2_}\nb1:\n{b2_}")

0 0.6942322
1000 0.47743034
2000 0.47739682
3000 0.4773901
4000 0.47738782
5000 0.47738677
6000 0.47738624
7000 0.477386
8000 0.4773859
9000 0.47738576
10000 0.4773857
11000 0.47738567
12000 0.47738564
13000 0.47738564
14000 0.47738564
15000 0.47738564
16000 0.47738564
17000 0.4773856
18000 0.47747386
19000 0.47738564
20000 0.47738564
21000 0.47738564
22000 0.47738564
23000 0.4773856
24000 0.4773998
25000 0.47738567
26000 0.47738564
27000 0.47738713
28000 0.47738564
29000 0.47738558
30000 0.47738564
31000 0.47738564
32000 0.4773856
33000 0.47738564
34000 0.47738558
35000 0.47738564
36000 0.47738564
37000 0.47738564
38000 0.47738558
39000 0.47738564
40000 0.47738564
41000 0.47738567
42000 0.47738612
43000 0.4773857
44000 0.47739094
45000 0.47738922
46000 0.47738564
47000 0.47738633
48000 0.4773856
49000 0.47738695

Hypothesis:
[[1.3133427e-11]
 [6.6668218e-01]
 [6.6668218e-01]
 [6.6668218e-01]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [1.]] 
Accuracy:
0.75

W1:
[[-29.426287 -13.975773]
 [-29.3699